### ISSUE TITLE
Ql 推送问题

### ISSUE THREAD

**Issue by Solmonz** [hex-ci/smzdm_script#42]
请问下是哪里设置错误了嘛 别的脚本可以正常推送 但是smzdm报错
（环境：最新版青龙）

telegram发送通知消息失败！！

RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:65)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:529:35)
    at origin.emit (/ql/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:571:11)
    at process.processTimers (node:internal/timers:512:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1712245724076,
    socket: 1712245724080,
    lookup: 1712245724081,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1712245739096,
    abort: undefined,
    phases: {
      wait: 4,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 15020
    }
  },
  event: 'request'
}

🔔smzdm 每日任务, 结束! 🕛 70.556 秒

**Comment by Solmonz** [comment]
不知道
